# Generated by Django 5.2.3 on 2025-06-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(
                help_text='Укажите chat-id в телеграмм', max_length=50, verbose_name='chat-id в телеграмм'
            ),
        ),
    ]
