# Generated by Django 5.2.3 on 2025-06-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_tg_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True,
                default='media/users/avatars/default.jpg',
                null=True,
                upload_to='users/avatars//%Y/%m/%d/',
                verbose_name='Аватвр',
            ),
        ),
    ]
