# Generated by Django 5.2.3 on 2025-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True,
                default='/media/users/avatars/default.jpg',
                null=True,
                upload_to='users/avatars/%Y/%m/%d/',
                verbose_name='Аватвр',
            ),
        ),
    ]
