# Generated by Django 5.2.3 on 2025-06-26 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Введите текст записи', verbose_name='Текст записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания записи')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='время изменения записи')),
                (
                    'mood',
                    models.CharField(
                        choices=[
                            ('👌', 'Норма'),
                            ('😊', 'Улыбка'),
                            ('😂', 'Смех'),
                            ('😒', 'Грусть'),
                            ('🤑', 'Деньги'),
                            ('😢', 'Слезы'),
                            ('🤢', 'Противно'),
                            ('😡', 'Злость'),
                            ('😈', 'Дьявол'),
                        ],
                        default='👌',
                        max_length=5,
                        verbose_name='Настроение',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entry',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Автор записи',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(blank=True, related_name='entry', to='diary.tag', verbose_name='Теги'),
                ),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-change_time'],
            },
        ),
    ]
