# Generated by Django 5.2.3 on 2025-06-28 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Автор тэга',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(
                choices=[
                    ('👌', 'Норма'),
                    ('😊', 'Улыбка'),
                    ('😂', 'Смех'),
                    ('😒', 'Грусть'),
                    ('😢', 'Слезы'),
                    ('😡', 'Злость'),
                ],
                default='👌',
                max_length=5,
                verbose_name='Настроение',
            ),
        ),
    ]
