# Generated by Django 5.2.3 on 2025-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_tag_owner_alter_entry_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=None, unique=True, verbose_name='slug'),
        ),
    ]
