# Generated by Django 5.2.3 on 2025-06-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
